theme: jekyll-theme-cayman
title: SFSpeckit
description: The Enterprise-Grade Salesforce AI-Driven Development (AIDD) Framework
author: Sumanth Yanamala
github:
  repository_url: https://github.com/ysumanth06/SF-Spec-Kit
show_downloads: true
google_analytics:
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
